# Generated by Django 4.2.15 on 2024-08-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0002_alter_watchlist_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='UNWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storyline', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdb_api.watchlist')),
            ],
        ),
    ]
