# Generated by Django 4.2.15 on 2024-09-05 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0005_alter_watchlist_platform_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='desc',
            field=models.CharField(default=datetime.datetime(2024, 9, 5, 18, 14, 58, 15385, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
