# Generated by Django 4.2.15 on 2024-09-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_api', '0007_review_user_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_review',
            new_name='review_user',
        ),
    ]
